# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run all tests of Emoji Art"
  lane :tests do
    # add actions here: https://docs.fastlane.tools/actions
    puts "============ Tests started (iPad 9th Gen.) ==========="
    scan(devices: ["iPad Pro (12.9-inch) (5th generation)"], clean: true)
    puts "============ Tests switch (iPhone 12 mini) ==========="
    scan(devices: ["iPhone 13 Pro"], clean: true)
    puts "============ Tests finished ==========="
  end
end